---
env:
  browser: true
  mocha: true
  node: true
  webextensions: true

extends:
  - airbnb
  - plugin:flowtype/recommended

parser: babel-eslint
parserOptions:
  ecmaVersion: 7

plugins:
  - chai-expect
  - chai-friendly
  - mocha-no-only
  - flowtype

rules:
  arrow-parens: 0
  class-methods-use-this: 0
  comma-dangle: 0
  consistent-return: 0
  curly: 0
  linebreak-style: 0
  lines-between-class-members: 0
  max-classes-per-file: 0
  max-len: 0
  no-await-in-loop: 0
  no-console:
    - warn
    - allow:
      - warn
      - error
  no-continue: 0
  no-mixed-operators: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: 0
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-unused-expressions: 0
  nonblock-statement-body-position: 0
  object-curly-newline: 0
  prefer-destructuring: 0
  spaced-comment: 0

  chai-expect/missing-assertion: 2
  chai-expect/terminating-properties: 1

  chai-friendly/no-unused-expressions: 2

  flowtype/boolean-style:
    - error
    - bool
  flowtype/no-primitive-constructor-types: 2
  flowtype/require-valid-file-annotation:
    - error
    - always

  import/no-named-as-default: 0
  import/prefer-default-export: 0

  mocha-no-only/mocha-no-only:
    - error

  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/destructuring-assignment: 0
  react/require-default-props: 0
  react/sort-comp: 0
  react/jsx-filename-extension: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-props-no-spreading: 0
  react/state-in-constructor: 0
  react/static-property-placement: 0
