image: registry.gitlab.com/tankerhq/docker/node:latest

stages:
  - check
  - deploy

default:
  before_script:
    - poetry -V
    - node -v
    - poetry install
    - poetry run python --version

check/linux:
  stage: check
  except:
    - schedules
  script:
    - poetry run python run-ci.py check --runner linux
    - mv coverage/lcov-report lcov-report
  artifacts:
    paths:
      - lcov-report/
    expire_in: 7 days
  tags:
    - linux

check/macos:
  stage: check
  except:
    - schedules
  script:
    - poetry run python run-ci.py check --runner macos
  tags:
    - macos

.check/windows:
  stage: check
  tags:
    - windows

check/windows/edge:
  extends: .check/windows
  script:
    - poetry run python run-ci.py check --runner windows-edge

check/windows/ie:
  extends: .check/windows
  only:
    - master
  script:
    - poetry run python run-ci.py check --runner windows-ie

check/windows/ie/manual:
  extends: .check/windows
  when: manual
  except:
    - master
  script:
    - poetry run python run-ci.py check --runner windows-ie

check/linux/nightly:
  stage: check
  only:
    - schedules
  script:
    - poetry run python run-ci.py check --runner linux --nightly
  tags:
    - linux

# Benchmark jobs are pinned on a machine to have more consistent results.

check/linux/benchmark-nightly:
  stage: check
  only:
    - schedules
  script:
    - poetry run python run-ci.py benchmark --runner linux
  tags:
    - LinuxSlave-3

check/macos/benchmark-nightly:
  stage: check
  only:
    - schedules
  script:
    - poetry run python run-ci.py benchmark --runner macos
  tags:
    - MacOSSlave-2

check/windows/benchmark-nightly:
  stage: check
  only:
    - schedules
  script:
    - poetry run python run-ci.py benchmark --runner windows-edge
  tags:
    - WindowsSlave-2

check/macos/nightly:
  stage: check
  only:
    - schedules
  script:
    - poetry run python run-ci.py check --runner macos --nightly
  tags:
    - macos

.deploy:
  stage: deploy
  except:
    - schedules
  tags:
    - linux

deploy/sdk:
  extends: .deploy
  environment:
    name: prod
  only:
    - /\Av[0-9.]+(-(alpha|beta)[0-9]+)?\z/
  script:
    - poetry run python run-ci.py deploy
        --env ${CI_ENVIRONMENT_NAME} --git-tag ${CI_COMMIT_TAG}

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master

  except:
    - schedules
  script:
    - poetry run python run-ci.py mirror

pages:
  stage: deploy
  only:
    - master
  except:
    - schedules
  dependencies:
    - check/linux
  script:
    - mv lcov-report/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

check/compat:
  stage: check
  when: manual
  except:
    - master
  script:
    - poetry run python run-ci.py compat
  tags:
    - linux

check/compat/master:
  stage: check
  only:
    - master
  script:
    - poetry run python run-ci.py compat
  tags:
    - linux

.check/e2e:
  stage: check
  script:
    - poetry run python run-ci.py e2e
  tags:
    - linux
  image: registry.gitlab.com/tankerhq/docker/e2e:latest

check/e2e:
  extends: .check/e2e
  when: manual
  except:
    - schedules

check/e2e/nightly:
  extends: .check/e2e
  only:
    - schedules

audit:
  stage: check
  script:
    - yarn
    - yarn audit
  only:
    - schedules
