[tool.poetry]
name = "tanker-js-sdk"
version = "0.1.0"
description = "Tanker Javascript client"
authors = ["Tanker dev team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
cli_ui = "^0.10.3"
path = "^13.2.0"
psutil = "^5.7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "0.740"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
