[version]
current = "0.0.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "packages/client-browser/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/core": "{current_version}"'

[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/datastore-dexie-browser": "{current_version}"'

[[file]]
src = "packages/client-node/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/core": "{current_version}"'

[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/datastore-pouchdb-node": "{current_version}"'

[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/datastore-pouchdb-memory": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"@tanker/datastore-base": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"@tanker/errors": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"@tanker/stream-base": "{current_version}"'

[[file]]
src = "packages/core/package.json"
search = '"@tanker/datastore-pouchdb-memory": "{current_version}"'

[[file]]
src = "packages/core/src/version.js"
search = "TANKER_SDK_VERSION = '{current_version}'"

[[file]]
src = "packages/crypto/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/base/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/base/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/datastore/dexie-browser/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/dexie-browser/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-base/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-base/package.json"
search = '"@tanker/datastore-base": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-memory/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-memory/package.json"
search = '"@tanker/datastore-pouchdb-base": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-node/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/datastore/pouchdb-node/package.json"
search = '"@tanker/datastore-pouchdb-base": "{current_version}"'

[[file]]
src = "packages/datastore/tests/package.json"
search = '"@tanker/datastore-base": "{current_version}"'

[[file]]
src = "packages/errors/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/file-polyfill/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/file-polyfill/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/stream/base/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/stream/base/package.json"
search = '"@tanker/errors": "{current_version}"'

[[file]]
src = "packages/stream/base/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/stream/browser/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/errors": "{current_version}"'

[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/file-polyfill": "{current_version}"'

[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/stream-base": "{current_version}"'

[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/crypto": "{current_version}"'

[[file]]
src = "packages/stream/node/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/stream/node/package.json"
search = '"@tanker/errors": "{current_version}"'

[[file]]
src = "packages/stream/node/package.json"
search = '"@tanker/stream-base": "{current_version}"'

[[file]]
src = "packages/stream/node/package.json"
search = '"@tanker/crypto": "{current_version}"'
