[version]
current = "0.0.1"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (
    -
    (?P<channel>alpha|beta|r)
    (?P<release>\d+)
  )?
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"


[[file]]
src = "packages/client-browser/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/core": "{current_version}"'
[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/datastore-dexie-browser": "{current_version}"'
[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/file-ponyfill": "{current_version}"'
[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/file-reader": "{current_version}"'
[[file]]
src = "packages/client-browser/package.json"
search = '"@tanker/stream-browser": "{current_version}"'


[[file]]
src = "packages/client-node/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/core": "{current_version}"'
[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/datastore-pouchdb-node": "{current_version}"'
[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/stream-node": "{current_version}"'
[[file]]
src = "packages/client-node/package.json"
search = '"@tanker/datastore-pouchdb-memory": "{current_version}"'


[[file]]
src = "packages/core/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/crypto": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/datastore-base": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/errors": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/identity": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/stream-base": "{current_version}"'
[[file]]
src = "packages/core/package.json"
search = '"@tanker/datastore-pouchdb-memory": "{current_version}"'
[[file]]
src = "packages/core/src/version.js"
search = "TANKER_SDK_VERSION = '{current_version}'"


[[file]]
src = "packages/crypto/package.json"
search = '"version": "{current_version}"'


[[file]]
src = "packages/datastore/base/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/datastore/base/package.json"
search = '"@tanker/crypto": "{current_version}"'


[[file]]
src = "packages/datastore/dexie-browser/package.json"
search = '"version": "{current_version}"'


[[file]]
src = "packages/datastore/pouchdb-base/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/datastore/pouchdb-base/package.json"
search = '"@tanker/datastore-base": "{current_version}"'


[[file]]
src = "packages/datastore/pouchdb-memory/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/datastore/pouchdb-memory/package.json"
search = '"@tanker/datastore-pouchdb-base": "{current_version}"'


[[file]]
src = "packages/datastore/pouchdb-node/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/datastore/pouchdb-node/package.json"
search = '"@tanker/datastore-pouchdb-base": "{current_version}"'


[[file]]
src = "packages/errors/package.json"
search = '"version": "{current_version}"'


[[file]]
src = "packages/file-ponyfill/package.json"
search = '"version": "{current_version}"'


[[file]]
src = "packages/file-reader/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/file-reader/package.json"
search = '"@tanker/file-ponyfill": "{current_version}"'


[[file]]
src = "packages/identity/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/identity/package.json"
search = '"@tanker/crypto": "{current_version}"'
[[file]]
src = "packages/identity/package.json"
search = '"@tanker/errors": "{current_version}"'


[[file]]
src = "packages/stream/base/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/stream/base/package.json"
search = '"@tanker/errors": "{current_version}"'


[[file]]
src = "packages/stream/browser/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/errors": "{current_version}"'
[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/file-ponyfill": "{current_version}"'
[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/file-reader": "{current_version}"'
[[file]]
src = "packages/stream/browser/package.json"
search = '"@tanker/stream-base": "{current_version}"'


[[file]]
src = "packages/stream/node/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/stream/node/package.json"
search = '"@tanker/errors": "{current_version}"'
[[file]]
src = "packages/stream/node/package.json"
search = '"@tanker/stream-base": "{current_version}"'


[[file]]
src = "packages/filekit/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/filekit/package.json"
search = '"@tanker/client-browser": "{current_version}"'
[[file]]
src = "packages/filekit/package.json"
search = '"@tanker/storage": "{current_version}"'
[[file]]
src = "packages/filekit/package.json"
search = '"@tanker/verification-ui": "{current_version}"'


[[file]]
src = "packages/storage/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/storage/package.json"
search = '"@tanker/client-browser": "{current_version}"'


[[file]]
src = "packages/fake-authentication/package.json"
search = '"version": "{current_version}"'
[[file]]
src = "packages/fake-authentication/package.json"
search = '"@tanker/client-browser": "{current_version}"'


[[file]]
src = "packages/verification-ui/node/package.json"
search = '"version": "{current_version}"'

[[file]]
src = "packages/verification-ui/node/package.json"
search = '"@tanker/client-browser": "{current_version}"'

[[file]]
src = "packages/verification-ui/node/package.json"
search = '"@tanker/identity": "{current_version}"'

