name: tests

on: [push]

jobs:
  run_tests:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry install
    - name: Run tests
      run: poetry run python run-ci.py check --runner windows-ie
      env:
        TANKER_TRUSTCHAIND_URL: ${{ secrets.TANKER_TRUSTCHAIND_URL }}
        TANKER_ADMIND_URL: ${{ secrets.TANKER_ADMIND_URL }}
        TANKER_EMAILD_URL: ${{ secrets.TANKER_EMAILD_URL }}
        TANKER_FAKE_AUTH_URL: ${{ secrets.TANKER_FAKE_AUTH_URL }}
        TANKER_DASHBOARD_URL: ${{ secrets.TANKER_DASHBOARD_URL }}
        TANKER_ID_TOKEN: ${{ secrets.TANKER_ID_TOKEN }}
        TANKER_EMAILD_TEST_TOKEN: ${{ secrets.TANKER_EMAILD_TEST_TOKEN }}
        TANKER_OIDC_PROVIDER: ${{ secrets.TANKER_OIDC_PROVIDER }}
        TANKER_OIDC_CLIENT_ID: ${{ secrets.TANKER_OIDC_CLIENT_ID }}
        TANKER_OIDC_CLIENT_SECRET: ${{ secrets.TANKER_OIDC_CLIENT_SECRET }}
        TANKER_OIDC_MARTINE_EMAIL: ${{ secrets.TANKER_OIDC_MARTINE_EMAIL }}
        TANKER_OIDC_MARTINE_REFRESH_TOKEN: ${{ secrets.TANKER_OIDC_MARTINE_REFRESH_TOKEN }}
        TANKER_OIDC_KEVIN_EMAIL: ${{ secrets.TANKER_OIDC_KEVIN_EMAIL }}
        TANKER_OIDC_KEVIN_REFRESH_TOKEN: ${{ secrets.TANKER_OIDC_KEVIN_REFRESH_TOKEN }}
        TANKER_FILEKIT_BUCKET_NAME: ${{ secrets.TANKER_FILEKIT_BUCKET_NAME }}
        TANKER_FILEKIT_BUCKET_REGION: ${{ secrets.TANKER_FILEKIT_BUCKET_REGION }}
        TANKER_FILEKIT_CLIENT_ID: ${{ secrets.TANKER_FILEKIT_CLIENT_ID }}
        TANKER_FILEKIT_CLIENT_SECRET: ${{ secrets.TANKER_FILEKIT_CLIENT_SECRET }}
